version: "3"
services:
  postgres:
    image: postgres
    network_mode: bridge
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: apicurio-registry
      POSTGRES_PASSWORD: password
  registry:
    image: apicurio/apicurio-registry-jpa
    network_mode: bridge
    container_name: registry
    ports:
      - 8081:8080
    environment:
      QUARKUS_DATASOURCE_URL: 'jdbc:postgresql://172.17.0.1:5432/apicurio-registry'
      QUARKUS_DATASOURCE_USERNAME: apicurio-registry
      QUARKUS_DATASOURCE_PASSWORD: password
  zookeeper:
    image: zookeeper
    network_mode: bridge
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: wurstmeister/kafka
    network_mode: bridge
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      #HOSTNAME_COMMAND: "ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $$1}'"
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: 172.17.0.1:2181
    depends_on:
      - zookeeper
